# This workflow is to run tests on regular pushes and pull requests - it is
# separate from the tests that get run during an auto-update, which can be
# found in update_and_publish.yml

name: Run tests

on:
  push:
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@924441154cf3053034c6513d5e06c69d262fb9a6  # v1.13.0
    with:
      envs: |
        - linux: py310-test
        - macos: py311-test
        - windows: py312-test-astropydev
